### ISSUE TITLE
Building Window binary from Mac

### ISSUE THREAD

**Issue by tovganesh** [bromix/vue-electron-app#4]
Could you tell how can a Windows binary be build from Mac.
Docs of electron-builder indicate that --windows flag can be used. However, using the same with npm run electron:build has no effect.

**Comment by bromix** [comment]
Sorry no, I always on the target platform it self. Please see the documentation of electron-builder [electron-builder
Multi Platform Build](https://www.electron.build/multi-platform-build.html) and also see the problem on Mac => [Can not build the windows installer on macOS Catalina version 10.15](https://github.com/electron-userland/electron-builder/issues/4305).

Your only change is:
```
electron-builder --win --x64
```

But more help I can't provide, sorry.
